apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: semaphore
            - name: POSTGRES_PASSWORD
              value: semaphore
            - name: POSTGRES_USER
              value: semaphore
          image: postgres:latest
          name: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: semaphore-postgres
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      hostname: postgres
      restartPolicy: Always
      volumes:
        - name: semaphore-postgres
          persistentVolumeClaim:
            claimName: semaphore-postgres
