apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: semaphore-postgres
  name: semaphore-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
